import { JobPost } from '../types';

export const INITIAL_JOB_POSTS: JobPost[] = [
  // 1. Government Jobs
  {
    id: 'post-govt-1',
    title: 'SSC CGL 2026 Recruitment Notification Out (17,500+ Vacancies)',
    organization: 'Staff Selection Commission (SSC)',
    category: 'govt_jobs',
    department: 'Central Government Departments & Ministries',
    location: 'All India',
    totalVacancies: 17727,
    salary: '₹35,400 - ₹1,42,400/- (Pay Level 4 to Level 8)',
    qualification: 'Graduate',
    summary: 'Staff Selection Commission has released the official notification for Combined Graduate Level Examination (CGL 2026) for Group B & C Assistant, Inspector & Auditor posts.',
    details: `The Staff Selection Commission will conduct the Combined Graduate Level Examination 2026 for recruitment to various Group 'B' and Group 'C' posts in different Ministries/ Departments/ Organizations of the Government of India.

### Selection Process
1. Tier-I Examination (Computer Based Test)
2. Tier-II Examination (Computer Based Test)
3. Document Verification & Medical Examination

### Important Instructions
Candidates must ensure that they fulfill all eligibility requirements before applying online. Digital passport photographs with live capture features must be submitted during registration.`,
    importantDates: {
      startDate: '2026-07-24',
      lastDate: '2026-08-28',
      feeLastDate: '2026-08-29',
      examDate: 'October - November 2026',
      admitCardDate: '7 days before exam',
    },
    applicationFee: {
      generalObcEws: '₹100',
      scStPwd: '₹0 (Exempted)',
      female: '₹0 (Exempted)',
      paymentMode: 'Online via Debit Card, Credit Card, Net Banking, or UPI',
    },
    ageLimit: {
      minAge: '18 Years',
      maxAge: '30 Years',
      asOnDate: '2026-08-01',
      relaxationDetails: 'OBC: 3 Years, SC/ST: 5 Years, PwD: 10 Years',
    },
    vacancies: [
      { postName: 'Assistant Section Officer (ASO)', totalPosts: 3200, eligibility: 'Bachelor Degree in Any Stream' },
      { postName: 'Inspector (Central Excise & Income Tax)', totalPosts: 4500, eligibility: 'Bachelor Degree in Any Stream' },
      { postName: 'Assistant Audit Officer (AAO)', totalPosts: 1200, eligibility: 'Bachelor Degree (Commerce/CA preferred)' },
      { postName: 'Tax Assistant & Auditor', totalPosts: 8827, eligibility: 'Bachelor Degree with Typing Proficiency' },
    ],
    applyUrl: 'https://ssc.gov.in',
    notificationPdfUrl: 'https://ssc.gov.in/pdf/notice_cgl_2026.pdf',
    officialWebsiteUrl: 'https://ssc.gov.in',
    syllabusPdfUrl: 'https://ssc.gov.in/pdf/cgl_syllabus_2026.pdf',
    isFeatured: true,
    status: 'Active',
    postedDate: '2026-07-24',
    viewsCount: 14250,
  },
  {
    id: 'post-govt-2',
    title: 'Railway RRC Group D Recruitment 2026 (1,03,769 Posts)',
    organization: 'Railway Recruitment Cell (RRC / RRB)',
    category: 'govt_jobs',
    department: 'Indian Railways (Various Zones)',
    location: 'Across India',
    totalVacancies: 103769,
    salary: '₹18,000 - ₹56,900/- (Pay Level 1 + Allowances)',
    qualification: '10th',
    summary: 'Indian Railways invites online applications for 1,03,769 Track Maintainer, Helper, Assistant Pointsman, and Level-1 posts.',
    details: `Railway Recruitment Boards (RRBs) are conducting nationwide recruitment for Level-1 posts under 7th CPC Pay Matrix. High volume hiring across Northern, Southern, Eastern, Western, and Central Railway zones.

### Physical Efficiency Test (PET) Criteria
- **Male Candidates**: Carry 35 kg weight for 100 meters in 2 minutes + Run 1000 meters in 4 min 15 sec.
- **Female Candidates**: Carry 20 kg weight for 100 meters in 2 minutes + Run 1000 meters in 5 min 40 sec.`,
    importantDates: {
      startDate: '2026-08-01',
      lastDate: '2026-09-15',
      feeLastDate: '2026-09-16',
      examDate: 'December 2026',
    },
    applicationFee: {
      generalObcEws: '₹500 (₹400 Refunded after CBT)',
      scStPwd: '₹250 (₹250 Refunded after CBT)',
      female: '₹250 (₹250 Refunded after CBT)',
      paymentMode: 'Online Payment Gateway',
    },
    ageLimit: {
      minAge: '18 Years',
      maxAge: '33 Years',
      asOnDate: '2026-07-01',
      relaxationDetails: 'SC/ST: 5 Years, OBC: 3 Years',
    },
    vacancies: [
      { postName: 'Track Maintainer Grade IV', totalPosts: 40100, eligibility: '10th Pass or ITI from NCVT/SCVT' },
      { postName: 'Helper / Assistant (Mechanical & Electrical)', totalPosts: 35000, eligibility: '10th Pass or ITI' },
      { postName: 'Pointsman Grade II', totalPosts: 28669, eligibility: '10th Pass' },
    ],
    applyUrl: 'https://rrbapply.gov.in',
    notificationPdfUrl: 'https://rrbapply.gov.in/docs/cen_groupd_2026.pdf',
    officialWebsiteUrl: 'https://indianrailways.gov.in',
    isFeatured: true,
    status: 'Active',
    postedDate: '2026-08-01',
    viewsCount: 28900,
  },
  {
    id: 'post-govt-3',
    title: 'IBPS PO XIV Online Form 2026 (4,455 Probationary Officer Posts)',
    organization: 'Institute of Banking Personnel Selection (IBPS)',
    category: 'govt_jobs',
    department: 'Participating Public Sector Banks',
    location: 'All India',
    totalVacancies: 4455,
    salary: '₹52,000 - ₹65,000/- per month initial in-hand',
    qualification: 'Graduate',
    summary: 'IBPS has released notification for Probationary Officers/ Management Trainees in Bank of Baroda, PNB, Canara Bank, Union Bank, and others.',
    details: `Online registration for IBPS PO/MT XIV is currently open. Candidates seeking a rewarding career in nationalized banking can register now. Preliminary exam consists of English, Quantitative Aptitude, and Reasoning Ability.`,
    importantDates: {
      startDate: '2026-08-01',
      lastDate: '2026-08-21',
      feeLastDate: '2026-08-21',
      examDate: 'October 2026 (Prelims)',
      admitCardDate: 'September 2026',
    },
    applicationFee: {
      generalObcEws: '₹850',
      scStPwd: '₹175',
      female: '₹850',
      paymentMode: 'Online Payment',
    },
    ageLimit: {
      minAge: '20 Years',
      maxAge: '30 Years',
      asOnDate: '2026-08-01',
      relaxationDetails: 'OBC: 3 yrs, SC/ST: 5 yrs',
    },
    applyUrl: 'https://ibps.in',
    notificationPdfUrl: 'https://ibps.in/pdf/po_xiv_advt.pdf',
    officialWebsiteUrl: 'https://ibps.in',
    status: 'Closing Soon',
    postedDate: '2026-08-01',
    viewsCount: 9800,
  },

  // 2. Private Jobs
  {
    id: 'post-private-1',
    title: 'TCS NQT Hiring Drive 2026 - Software Engineers & Analysts',
    organization: 'Tata Consultancy Services (TCS)',
    category: 'private_jobs',
    location: 'Pan India (Bengaluru, Hyderabad, Pune, Noida, Kolkata)',
    totalVacancies: 15000,
    salary: '₹3.66 LPA to ₹9.0 LPA (Ninja & Digital Roles)',
    qualification: 'Engineering',
    summary: 'TCS National Qualifier Test (NQT) is hiring Freshers (2025 & 2026 Passouts) for TCS Ninja, Digital, and Prime engineering roles.',
    details: `TCS is inviting applications from B.E. / B.Tech / M.E. / M.Tech / MCA / M.Sc graduates for national off-campus hiring. Test covers Cognitive Skills and Advanced Coding skills.`,
    importantDates: {
      startDate: '2026-07-20',
      lastDate: '2026-08-25',
      examDate: 'September 2026',
    },
    applicationFee: {
      generalObcEws: '₹0 (Free)',
      scStPwd: '₹0 (Free)',
      female: '₹0 (Free)',
      paymentMode: 'No Fee Required',
    },
    ageLimit: {
      minAge: '18 Years',
      maxAge: '28 Years',
    },
    applyUrl: 'https://nextstep.tcs.com',
    notificationPdfUrl: 'https://tcs.com/careers/nqt2026_guidelines.pdf',
    officialWebsiteUrl: 'https://tcs.com/careers',
    isFeatured: true,
    status: 'Active',
    postedDate: '2026-07-20',
    viewsCount: 18400,
  },
  {
    id: 'post-private-2',
    title: 'Infosys Specialist Programmer & System Engineer Drive 2026',
    organization: 'Infosys Limited',
    category: 'private_jobs',
    location: 'Hybrid / Multiple Cities',
    totalVacancies: 8500,
    salary: '₹3.6 LPA - ₹9.5 LPA',
    qualification: 'Graduate',
    summary: 'Infosys off-campus recruitment drive for fresh software developers, cloud engineers, and data analysts across India.',
    details: `Opportunities for recent graduates to join Infosys innovation centers. Selection via online assessment followed by technical & HR interview.`,
    importantDates: {
      startDate: '2026-07-28',
      lastDate: '2026-08-30',
    },
    applicationFee: {
      generalObcEws: '₹0',
      scStPwd: '₹0',
      female: '₹0',
      paymentMode: 'Free',
    },
    applyUrl: 'https://career.infosys.com',
    notificationPdfUrl: 'https://career.infosys.com/notice2026.pdf',
    officialWebsiteUrl: 'https://infosys.com',
    status: 'Active',
    postedDate: '2026-07-28',
    viewsCount: 11200,
  },

  // 3. Admit Card
  {
    id: 'post-admit-1',
    title: 'SSC CHSL Tier-I Exam 2026 Admit Card Released',
    organization: 'Staff Selection Commission (SSC)',
    category: 'admit_card',
    location: 'All India Regions (NR, CR, WR, ER, SR, KKR, NWR)',
    totalVacancies: 3712,
    salary: 'Level 2 & Level 4',
    qualification: '12th',
    summary: 'Download SSC CHSL Tier 1 Hall Ticket / Application Status for all regional websites.',
    details: `SSC CHSL 10+2 Tier 1 Computer Based Examination hall tickets are live now. Login with Registration ID and Date of Birth to download your admit card. Bring original Photo ID proof to exam center.`,
    importantDates: {
      startDate: '2026-08-02',
      lastDate: '2026-08-20',
      examDate: 'August 12 - August 22, 2026',
      admitCardDate: '2026-08-02',
    },
    applyUrl: 'https://ssc.gov.in/admit-card',
    notificationPdfUrl: 'https://ssc.gov.in/pdf/chsl_admitcard_notice.pdf',
    officialWebsiteUrl: 'https://ssc.gov.in',
    isFeatured: true,
    status: 'Active',
    postedDate: '2026-08-02',
    viewsCount: 22100,
  },
  {
    id: 'post-admit-2',
    title: 'NEET UG 2026 Re-Exam Admit Card Download',
    organization: 'National Testing Agency (NTA)',
    category: 'admit_card',
    location: 'National Centers',
    totalVacancies: 0,
    salary: 'N/A (Entrance Exam)',
    qualification: '12th Science',
    summary: 'NTA has uploaded the hall ticket for candidates appearing in NEET UG 2026 Special Test.',
    details: `Candidates can download their admit card using Application Number, Date of Birth, and Security Pin from the NTA NEET portal.`,
    importantDates: {
      startDate: '2026-08-03',
      lastDate: '2026-08-10',
      examDate: '2026-08-10',
      admitCardDate: '2026-08-03',
    },
    applyUrl: 'https://neet.nta.nic.in',
    notificationPdfUrl: 'https://neet.nta.nic.in/docs/admitcard_press_release.pdf',
    officialWebsiteUrl: 'https://nta.ac.in',
    status: 'Active',
    postedDate: '2026-08-03',
    viewsCount: 16800,
  },

  // 4. Results
  {
    id: 'post-result-1',
    title: 'UPSC Civil Services (IAS/IFS) Prelims 2026 Name & Roll List Result',
    organization: 'Union Public Service Commission (UPSC)',
    category: 'results',
    location: 'All India',
    totalVacancies: 1056,
    salary: 'Pay Level 10 (Group A Gazetted)',
    qualification: 'Graduate',
    summary: 'UPSC CSE Prelims 2026 Qualified Candidates PDF List released for Mains Examination.',
    details: `UPSC has declared the result for Civil Services Preliminary Examination held in May 2026. Successful candidates must fill DAF-I for Civil Services (Mains) Exam.`,
    importantDates: {
      startDate: '2026-08-01',
      lastDate: '2026-09-01',
      resultDate: '2026-08-01',
    },
    applyUrl: 'https://upsc.gov.in/written-results',
    notificationPdfUrl: 'https://upsc.gov.in/pdf/cse_pre_2026_result_list.pdf',
    officialWebsiteUrl: 'https://upsc.gov.in',
    isFeatured: true,
    status: 'Active',
    postedDate: '2026-08-01',
    viewsCount: 31000,
  },
  {
    id: 'post-result-2',
    title: 'SBI PO Phase-II Main Exam Result 2026 Declared',
    organization: 'State Bank of India (SBI)',
    category: 'results',
    location: 'Pan India',
    totalVacancies: 2000,
    salary: '₹48,480/- + Allowances',
    qualification: 'Graduate',
    summary: 'Check SBI Probationary Officer Mains Result 2026 and Interview Call Letter details.',
    details: `State Bank of India has published the roll numbers of candidates shortlisted for Phase-III (Psychometric Test, Group Exercise & Interview).`,
    importantDates: {
      startDate: '2026-08-04',
      lastDate: '2026-08-25',
      resultDate: '2026-08-04',
    },
    applyUrl: 'https://sbi.co.in/careers',
    notificationPdfUrl: 'https://sbi.co.in/documents/po_mains_result2026.pdf',
    officialWebsiteUrl: 'https://sbi.co.in',
    status: 'Active',
    postedDate: '2026-08-04',
    viewsCount: 19500,
  },

  // 5. Syllabus
  {
    id: 'post-syllabus-1',
    title: 'UPSC NDA & NA (II) Exam 2026 Updated Detailed Syllabus & Pattern',
    organization: 'UPSC / Defense Forces',
    category: 'syllabus',
    location: 'All India',
    totalVacancies: 404,
    salary: 'Stipend ₹56,100/- during training',
    qualification: '12th',
    summary: 'Download topic-wise Mathematics and General Ability Test (GAT) syllabus along with marking scheme.',
    details: `Comprehensive subject breakdown for NDA 2 2026 examination:
- **Mathematics (300 Marks)**: Algebra, Matrices, Trigonometry, Analytical Geometry, Differential & Integral Calculus, Vector Algebra, Statistics & Probability.
- **GAT (600 Marks)**: Part A English (200 marks), Part B General Knowledge (Physics, Chemistry, General Science, History, Geography, Current Events - 400 marks).`,
    importantDates: {
      startDate: '2026-07-15',
      lastDate: '2026-10-01',
      examDate: 'September 2026',
    },
    applyUrl: 'https://upsc.gov.in',
    notificationPdfUrl: 'https://upsc.gov.in/pdf/nda2_syllabus_2026.pdf',
    officialWebsiteUrl: 'https://upsc.gov.in',
    syllabusPdfUrl: 'https://upsc.gov.in/pdf/nda2_syllabus_2026.pdf',
    status: 'Active',
    postedDate: '2026-07-15',
    viewsCount: 7400,
  },

  // 6. Admission
  {
    id: 'post-admission-1',
    title: 'IIT GATE 2027 Registration Open for M.Tech & Ph.D. Admissions',
    organization: 'Indian Institute of Technology (IIT Roorkee)',
    category: 'admission',
    location: 'National Institutes',
    totalVacancies: 0,
    salary: 'PGO Fellowship Stipend ₹12,400/pm',
    qualification: 'Engineering / Graduate',
    summary: 'Graduate Aptitude Test in Engineering (GATE 2027) application portal now open for engineers & science graduates.',
    details: `GATE 2027 score card is utilized for post-graduate admissions in IITs, NITs, IISc, and PSU recruitment without written exam.`,
    importantDates: {
      startDate: '2026-08-01',
      lastDate: '2026-09-29',
      examDate: 'February 2027',
    },
    applicationFee: {
      generalObcEws: '₹1800 per paper',
      scStPwd: '₹900 per paper',
      female: '₹900 per paper',
      paymentMode: 'GOAPS Online Portal',
    },
    applyUrl: 'https://gate2027.iitr.ac.in',
    notificationPdfUrl: 'https://gate2027.iitr.ac.in/docs/information_brochure.pdf',
    officialWebsiteUrl: 'https://gate2027.iitr.ac.in',
    status: 'Active',
    postedDate: '2026-08-01',
    viewsCount: 8900,
  },

  // 7. Scholarship
  {
    id: 'post-scholarship-1',
    title: 'National Means-cum-Merit Scholarship (NMMSS) 2026-27 Scheme',
    organization: 'Ministry of Education, Govt of India',
    category: 'scholarship',
    location: 'All States & UTs',
    totalVacancies: 100000,
    salary: '₹12,000/- per annum scholarship',
    qualification: '8th Pass (Studying in 9th)',
    summary: 'Scholarship scheme for meritorious students of economically weaker sections to arrest dropouts at class VIII.',
    details: `Selected students receive ₹1,000 per month (total ₹12,000 per annum) from Class IX to Class XII. Annual parent income must not exceed ₹3,500,00 per year.`,
    importantDates: {
      startDate: '2026-07-10',
      lastDate: '2026-10-15',
    },
    applyUrl: 'https://scholarships.gov.in',
    notificationPdfUrl: 'https://scholarships.gov.in/docs/nmmss_guidelines2026.pdf',
    officialWebsiteUrl: 'https://scholarships.gov.in',
    status: 'Active',
    postedDate: '2026-07-10',
    viewsCount: 12300,
  },

  // 8. Job News
  {
    id: 'post-news-1',
    title: 'Central Government Approves 50,000+ New Banking & Railway Posts',
    organization: 'Ministry of Finance & Railways',
    category: 'job_news',
    location: 'New Delhi / Nationwide',
    totalVacancies: 50000,
    salary: 'Various Pay Scales',
    qualification: '10th / 12th / Graduate',
    summary: 'Union Cabinet approves major mega hiring drive to fill vacant posts in public sector banks and Indian Railways by end of 2026.',
    details: `In a landmark announcement today, the Cabinet Committee on Economic Affairs approved expedited recruitment pipelines. Notifications for Bank Clerks, POs, Railway Technicians, and Loco Pilots will be published starting next month.`,
    importantDates: {
      startDate: '2026-08-04',
      lastDate: '2026-12-31',
    },
    applyUrl: 'https://pib.gov.in',
    notificationPdfUrl: 'https://pib.gov.in/pressrelease2026.pdf',
    officialWebsiteUrl: 'https://pib.gov.in',
    status: 'Active',
    postedDate: '2026-08-04',
    viewsCount: 25400,
  },

  // 9. Upcoming Exams
  {
    id: 'post-upcoming-1',
    title: 'SSC Stenographer Grade C & D Exam 2026 Calendar & Schedule',
    organization: 'Staff Selection Commission (SSC)',
    category: 'upcoming_exams',
    location: 'Nationwide Test Centers',
    totalVacancies: 2000,
    salary: 'Pay Level 4 & Level 6',
    qualification: '12th',
    summary: 'Upcoming notification announcement date, online submission window, and tentative CBT exam dates.',
    details: `SSC Examination Calendar indicates Stenographer Grade C & D official advertisement will be published on September 15, 2026. Skill test will follow CBT.`,
    importantDates: {
      startDate: '2026-09-15',
      lastDate: '2026-10-15',
      examDate: 'November 2026',
    },
    applyUrl: 'https://ssc.gov.in',
    notificationPdfUrl: 'https://ssc.gov.in/pdf/exam_calendar_2026.pdf',
    officialWebsiteUrl: 'https://ssc.gov.in',
    status: 'Active',
    postedDate: '2026-08-03',
    viewsCount: 6200,
  }
];
